### ISSUE TITLE
Allow usernames containing dots

### ISSUE THREAD

**Issue by ejpcmac** [ejpcmac/expected#1]
If the username contains one or more dots, the current implementation considers the authentication cookie as invalid. It should not.

**Comment by ejpcmac** [comment]
Currently, the cookie content is just splitted on dots and the result is pattern-matched:

https://github.com/ejpcmac/expected/blob/972bb361388967cb169792a1a61627b1df021ff3/lib/expected/plugs.ex#L245-L253

I think a correct implementation should use a regex to match any cookie that ends with two dot-separated base64-encoded values:

```elixir
case Regex.run(~r"(.*)\.([A-Za-z0-9+/=]*)\.([A-Za-z0-9+/=]*)", auth_cookie) do
  [_, user, serial, token] -> {:ok, user, serial, token}
  nil -> {:error, :invalid}
end
```

**Comment by rmoorman** [comment]
@ejpcmac how about encoding the "username" part too (base64)? You could still split on a dot and then decode the username.

**Comment by ejpcmac** [comment]
Yes, also. I’ll go for that!
